In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv("IMDb Movies India.csv",encoding='ISO-8859-1')

In [4]:
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,(1988),NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,(2005),NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,(1988),NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [5]:
data.isna().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
impute1=SimpleImputer(strategy='median')
impute2=SimpleImputer(strategy='mean')

In [8]:

data['Rating_mean'] = impute2.fit_transform(data[['Rating']])

In [9]:
data['Name']=data['Name'].str.replace("#","")

In [10]:
data['Name']

0
1        Gadhvi (He thought he was Gandhi)
2                               Homecoming
3                                   Yaaram
4                        ...And Once Again
                       ...
15504                  Zulm Ko Jala Doonga
15505                                Zulmi
15506                            Zulmi Raj
15507                        Zulmi Shikari
15508                         Zulm-O-Sitam
Name: Name, Length: 15509, dtype: object

In [11]:
data['Year']

0           NaN
1        (2019)
2        (2021)
3        (2019)
4        (2010)
          ...
15504    (1988)
15505    (1999)
15506    (2005)
15507    (1988)
15508    (1998)
Name: Year, Length: 15509, dtype: object

In [12]:
# Extract the year values using regular expressions
data['Year'] = data['Year'].str.extract(r'(\d{4})')

# Convert the 'Year' column to numeric if needed
data['Year'] = pd.to_numeric(data['Year'])

In [13]:
data['Year_median']=impute1.fit_transform(data[['Year']])

In [14]:

data['Year_median']=data['Year_median'].astype(int)

In [15]:
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,2021.0,90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,2010.0,105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,1988.0,NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,1999.0,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,2005.0,NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN,5.841621,2005
15507,Zulmi Shikari,1988.0,NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN,5.841621,1988
15508,Zulm-O-Sitam,1998.0,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [16]:
data=data

In [17]:
data['Duration']

0            NaN
1        109 min
2         90 min
3        110 min
4        105 min
          ...
15504        NaN
15505    129 min
15506        NaN
15507        NaN
15508    130 min
Name: Duration, Length: 15509, dtype: object

In [18]:
data['Duration']=data['Duration'].str.replace("min","")

In [19]:
data['Duration']=pd.to_numeric(data['Duration'])

In [20]:
data['Duration']=impute2.fit_transform(data[['Duration']])

In [21]:
data['Duration']=data['Duration'].astype(int)

In [22]:
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,NaN,128,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),2019.0,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,2021.0,90,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,2019.0,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,2010.0,105,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,1988.0,128,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,1999.0,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,2005.0,128,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN,5.841621,2005
15507,Zulmi Shikari,1988.0,128,Action,NaN,NaN,NaN,NaN,NaN,NaN,5.841621,1988
15508,Zulm-O-Sitam,1998.0,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [23]:
data.isna().sum()

Name              0
Year            528
Duration          0
Genre          1877
Rating         7590
Votes          7589
Director        525
Actor 1        1617
Actor 2        2384
Actor 3        3144
Rating_mean       0
Year_median       0
dtype: int64

In [24]:
data[['Actor 1','Actor 2','Actor 3','Director','Genre']]=data[['Actor 1','Actor 2','Actor 3','Director','Genre']].fillna('Unamed')

In [25]:
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,NaN,128,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),2019.0,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,2021.0,90,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,2019.0,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,2010.0,105,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,1988.0,128,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,1999.0,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,2005.0,128,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,1988.0,128,Action,NaN,NaN,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,1998.0,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [26]:
data.isna().sum()

Name              0
Year            528
Duration          0
Genre             0
Rating         7590
Votes          7589
Director          0
Actor 1           0
Actor 2           0
Actor 3           0
Rating_mean       0
Year_median       0
dtype: int64

In [27]:
data['Rating']=impute1.fit_transform(data[['Rating']])

In [28]:
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,NaN,128,Drama,6.0,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),2019.0,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,2021.0,90,"Drama, Musical",6.0,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,2019.0,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,2010.0,105,Drama,6.0,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,1988.0,128,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,1999.0,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,2005.0,128,Action,6.0,NaN,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,1988.0,128,Action,6.0,NaN,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,1998.0,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [29]:
data.isna().sum()

Name              0
Year            528
Duration          0
Genre             0
Rating            0
Votes          7589
Director          0
Actor 1           0
Actor 2           0
Actor 3           0
Rating_mean       0
Year_median       0
dtype: int64

In [30]:
data=data.drop('Year',axis=1)

In [31]:
data

,Name,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,128,Drama,6.0,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,90,"Drama, Musical",6.0,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,105,Drama,6.0,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,128,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,128,Action,6.0,NaN,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,128,Action,6.0,NaN,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [32]:
data

,Name,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,128,Drama,6.0,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,90,"Drama, Musical",6.0,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,105,Drama,6.0,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,128,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,128,Action,6.0,NaN,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,128,Action,6.0,NaN,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [33]:
data.head(6)

,Name,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,128,Drama,6.0,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,90,"Drama, Musical",6.0,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,105,Drama,6.0,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
5,...Aur Pyaar Ho Gaya,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,4.700000,1997

In [34]:
data['Votes'] = data['Votes'].fillna(0)

In [35]:
data

,Name,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,128,Drama,6.0,0,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,90,"Drama, Musical",6.0,0,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,105,Drama,6.0,0,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,128,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,128,Action,6.0,0,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,128,Action,6.0,0,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [36]:
data['Votes']=data['Votes'].str.replace(",","")

In [37]:
data['Votes']=data['Votes'].str.replace("$","")
data['Votes']=data['Votes'].str.replace("M","")
data['Votes']=data['Votes'].str.replace(".","")

In [38]:
data['Votes']=pd.to_numeric(data['Votes'])

In [39]:
data

,Name,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,128,Drama,6.0,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),109,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,90,"Drama, Musical",6.0,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,110,"Comedy, Romance",4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,105,Drama,6.0,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,128,Action,4.6,11.0,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,129,"Action, Drama",4.5,655.0,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,128,Action,6.0,NaN,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,128,Action,6.0,NaN,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,130,"Action, Drama",6.2,20.0,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [40]:
data['Votes']=impute2.fit_transform(data[['Votes']])

In [41]:
data

,Name,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Rating_mean,Year_median
0,,128,Drama,6.0,1938.340783,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,5.841621,1991
1,Gadhvi (He thought he was Gandhi),109,Drama,7.0,8.000000,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,7.000000,2019
2,Homecoming,90,"Drama, Musical",6.0,1938.340783,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,5.841621,2021
3,Yaaram,110,"Comedy, Romance",4.4,35.000000,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,4.400000,2019
4,...And Once Again,105,Drama,6.0,1938.340783,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,5.841621,2010
...,...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,128,Action,4.6,11.000000,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand,4.600000,1988
15505,Zulmi,129,"Action, Drama",4.5,655.000000,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,4.500000,1999
15506,Zulmi Raj,128,Action,6.0,1938.340783,Kiran Thej,Sangeeta Tiwari,Unamed,Unamed,5.841621,2005
15507,Zulmi Shikari,128,Action,6.0,1938.340783,Unamed,Unamed,Unamed,Unamed,5.841621,1988
15508,Zulm-O-Sitam,130,"Action, Drama",6.2,20.000000,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,6.200000,1998

In [42]:
data=data.drop(['Name','Director','Actor 1','Actor 2','Actor 3'],axis=1)

In [43]:
data

,Duration,Genre,Rating,Votes,Rating_mean,Year_median
0,128,Drama,6.0,1938.340783,5.841621,1991
1,109,Drama,7.0,8.000000,7.000000,2019
2,90,"Drama, Musical",6.0,1938.340783,5.841621,2021
3,110,"Comedy, Romance",4.4,35.000000,4.400000,2019
4,105,Drama,6.0,1938.340783,5.841621,2010
...,...,...,...,...,...,...
15504,128,Action,4.6,11.000000,4.600000,1988
15505,129,"Action, Drama",4.5,655.000000,4.500000,1999
15506,128,Action,6.0,1938.340783,5.841621,2005
15507,128,Action,6.0,1938.340783,5.841621,1988
15508,130,"Action, Drama",6.2,20.000000,6.200000,1998

In [44]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [45]:
ohe=OneHotEncoder()

In [46]:
ohe.fit(data[['Genre']])

OneHotEncoder()

In [47]:
genre_encoded = ohe.transform(data[['Genre']])

In [48]:
genre_encoded

<15509x486 sparse matrix of type '<class 'numpy.float64'>'
	with 15509 stored elements in Compressed Sparse Row format>

In [49]:
data=data.drop('Genre',axis=1)

In [50]:
data

       Duration  Rating        Votes  Rating_mean  Year_median
0           128     6.0  1938.340783     5.841621         1991
1           109     7.0     8.000000     7.000000         2019
2            90     6.0  1938.340783     5.841621         2021
3           110     4.4    35.000000     4.400000         2019
4           105     6.0  1938.340783     5.841621         2010
...         ...     ...          ...          ...          ...
15504       128     4.6    11.000000     4.600000         1988
15505       129     4.5   655.000000     4.500000         1999
15506       128     6.0  1938.340783     5.841621         2005
15507       128     6.0  1938.340783     5.841621         1988
15508       130     6.2    20.000000     6.200000         1998

[15509 rows x 5 columns]

In [51]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [52]:
X_train,X_test,y_train,y_test=train_test_split(data.drop('Rating_mean',axis=1),data['Rating_mean'],test_size=0.3)

In [53]:
clf1=LinearRegression()

In [54]:
clf1.fit(X_train,y_train)

LinearRegression()

In [55]:
y_pred=clf1.predict(X_test)

In [56]:
y_pred

array([5.90637494, 5.92204644, 5.88128948, ..., 5.92583778, 5.83901581,
       5.87655029])

In [57]:
score=clf1.score(X_train,y_train)

In [58]:
score

0.9942418766184069